'use client'
// import FaqSection from '@/components/Home/FaqSection';
import WhyInvestWithUs from '@/components/Home/WhyInvestWithUsSection';
import CowPurchaseSlider from '@/components/Project/cowSellProject/CowPurchaseSlider';
import 'swiper/css';
import 'swiper/css/pagination';
import InvestmentSection from '@/components/Helper/InvestmentSection';
import FaqSectionStatic from '@/components/service/Vet services/StaticFAQ';


const Project = () => {
  
  return (
    <div className='pt-16 lg:pt-20 overflow-hidden mt-[-10vh] lg:mt-[0vh]'>
        
        <div>
          <InvestmentSection/>
        </div>

      <div className='mt-20'>
        <CowPurchaseSlider />
      </div>

      <div className='my-20'>
        <WhyInvestWithUs />
      </div>

      <section className='bg-[#F6F4EC] py-10 text-center'>
        <FaqSectionStatic
  faqs={[
    {
      question: "What is this investment project about?",
      answer:
        "This project focuses on cattle rearing and beef fattening, where trained farmers raise cattle for sale during the Eid season, when demand and prices are highest, creating strong profit potential for investors.",
    },
    {
      question: "Where is the farm located?",
      answer:
        "The farms are located in Pakundia (Syed Ga), operated by experienced farmers who have been working with us under a structured system for over a year.",
    },
    {
      question: "How does this investment generate profit?",
      answer:
        "Profit is generated by raising healthy cattle using high-quality natural feed and selling them during Eid, when market prices peak. Investors earn returns from the final sale value.",
    },
    {
      question: "How much return can I expect?",
      answer:
        "The project aims to deliver returns that are over 1.5 times higher than traditional banks or financial institutions, depending on market conditions and project performance.",
    },
    {
      question: "Is my investment secure?",
      answer:
        "Yes. Your invested capital is protected through integrated livestock insurance coverage, reducing risks from disease, accidents, or unforeseen losses.",
    },
    {
      question: "How are the farms monitored?",
      answer:
        "Each farm is closely monitored by trained field agents and supported by dairy and veterinary experts from leading universities to ensure proper care and management.",
    },
    {
      question: "What kind of feed is used for the cattle?",
      answer:
        "We use high-quality, 100% natural feed with no artificial additives, resulting in healthier cattle and better-quality, safer beef.",
    },
    {
      question: "Who can invest in this project?",
      answer:
        "Anyone aged 18 or above can invest. This includes expatriates, women seeking halal investments, individuals buying cattle for Eid, retirees, entrepreneurs, fresh graduates, and anyone looking to diversify their savings.",
    },
    {
      question: "Can I invest for my own Eid cattle?",
      answer:
        "Yes. Investors can choose to invest for personal Eid consumption and receive healthy, well-raised cattle following ethical and safe food practices.",
    },
    {
      question: "How does this project help farmers?",
      answer:
        "Your investment enables farmers to access quality feed, veterinary care, and proper farm management, helping them grow sustainable businesses and improve their livelihoods.",
    },
    {
      question: "What makes this project different from traditional BORGA systems?",
      answer:
        "We have digitized and modernized the traditional BORGA system into a transparent, secure, and efficient platform with insurance-backed protection and professional oversight.",
    },
    {
      question: "Is this investment halal?",
      answer:
        "Yes. The project follows halal principles, ethical farming practices, and real asset-backed investment, making it suitable for halal-conscious investors.",
    },
  ]}
/>

      </section>
    </div>
  );
};

export default Project;
