import type { Metadata } from "next";
import {
  // Poppins,

  // Averia_Sans_Libre,
  Poppins,
} from "next/font/google";
import "./globals.css";

import NavBarResponsive from "@/components/Helper/NavBarResponsive";
import LenisProvider from "@/utils/LenisProvider";
import LoadingProvider from "@/components/Helper/LoadingProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"], // Add the required font weights
  style: ["normal", "italic"], // Optional styles
  variable: "--font-poppins",
});

// const averia = Averia_Sans_Libre({
//   subsets: ["latin"],
//   weight: ["400", "700"], // Specify weights as needed
// });

export const metadata: Metadata = {
  icons: "../favicon.ico",
  title: "Agri Core",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${poppins.className} antialiased bg-[#F6F4EC]/90`}>
        <NavBarResponsive />
        <LoadingProvider>
          <LenisProvider>
            <div className="">{children}</div>
          </LenisProvider>
        </LoadingProvider>

      </body>
    </html>
  );
}
